import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="min-h-screen bg-gray-900 flex flex-col md:flex-row">
      {/* Sidebar (Collapsible on small screens) */}
      <Sidebar />

      {/* Main Content */}
      <div className="flex-1 min-w-0 p-4">
        <div className="rounded-xl   bg-gray-800">{children}</div>
      </div>
    </div>
  );
}
